deploy:
  provider: releases
  api_key:
    secure: 6Es6sFcZpmalyRKaqU1oxTIXBh1zLfn8028UddG6kp1sEUGd5kIkGT+FeD5psDYy49P5BZNWB29YCp9EKO7sjJgX9PfyaIZaswIHB2TI0Aok9o76iD+PA2NCcfgPb4HUNRsWylaPO9xN7nsnQbbgreAVLdv57YuEhZa0LHi6/D25dRV8ihXcClJoAu7DQ4JSqNA/mEMwdAvs7KH89oTyffr3DPTTryZ3l8VdIg5JeIfa0nTbRhmJrZKUQEic9/Y+0VaSe0i1hW/qQ/b631cvBBlei5uBzLQkPYamqKfePljhVOkhVvq+zJKU7+uQ3+C26gzxGJEj7eemewkqLG4YurxGlKl3PBopRxeJY66jfBMu7js988pjzQNl3mo3iSYO/ei/bYxPSaeS7D82qEb2MVKr0Yr+kjwk7vvKFG4u90CBd42+KSWDJKO8UHYmQ6mUnFmWC6lSuDlKzj1rKIbOjXj1qyxzLOjc8RcZ26B2X2zoA3PGVx7NCVm319Y+N2SOId9ER4DYNjyaCXANNTXJCUCs6J/RjxIrkCjdHZN35cmHUATf35rI2LcSs55ztaHDt4b6/xbBvJOr1lnvVURPGt6YNokvEOadRUbgrkjSurxf7vqHepW0aS2vveZRPEjcESQ7ZHTkGelfGrVApwi07YuPzSuvsdbJZAU5ux6lMNU=
  file: ci-.tgz
  on:
    repo: $TRAVIS_REPO_SLUG
